apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: shahab5191/shinshingame-auth
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: postgres_password
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: postgres_username
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: jwt_secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 4000
    targetPort: 4000
